Repository CruGlobal/appbuilder_class_core, pull requests merged in 2024-11, with the labels that each got.

#258 Prevent updates from being added to DCs that are following another
  ABDataCollectionCore.js
Labels: patch

#259 fix type error found by sentry
  FilterComplexCore.js
Labels: patch

#260 *Fix undefined of index fields
  FilterComplexCore.js
Labels: patch

#264 *Fix pull value of Relational data
  FilterComplexCore.js
Labels: patch

#266 Fix our formio formatting to display the proper data
  ABObjectCore.js
  dataFields/ABFieldConnectCore.js
Labels: patch

#263 Current Netsuite API code
  ABFactoryCore.js
  ABModelCore.js
  ABObjectApiNetsuiteCore.js
  FilterComplexCore.js
  version
Labels: enhancement

#268 Add widget to set cursor in DC
  ABViewManagerCore.js
  views/ABViewDataSelectCore.js
Labels: minor

#267 Ensure Recalculates are passed through to the relevant methods
  dataFields/ABFieldCalculateCore.js
Labels: patch

#270 +Add hidden fields setting
  views/ABViewCSVExporterCore.js
Labels: patch
