Repository CruGlobal/appbuilder_class_core, pull requests merged in 2025-07, with the labels that each got.

#309 Update README.md
  README.md
Labels: minor

#310 fix secret name
  .github/workflows/pr-merge-release.yml
Labels: patch

#311 Fix formula field issues
  ABDataCollectionCore.js
Labels: bug, patch
