Repository CruGlobal/appbuilder_class_core, pull requests merged in 2025-06, with the labels that each got.

#303 DataCollections manage in_data_collection filter updates properly
  ABDataCollectionCore.js
Labels: patch

#306 Update organization
  .github/workflows/addissuetoproject.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/pr-label-check.yml
  .github/workflows/pr-merge-release.yml
  FilterComplexCore.js
  process/tasks/ABProcessTaskUserApprovalCore.js
Labels: skip-release

#307 Fix bugs
  ABProcessCore.js
  FilterComplexCore.js
Labels: bug, patch

#305 Add API Request Service
  process/ABProcessTaskManager.js
  process/tasks/ABProcessTaskServiceApiCore.js
Labels: minor
